config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'sessions/logout'
  devise_for :users

  resources :users
  resources :cars do
    collection do
      get 'manager_cars/:user_id', action: :manager_cars
    end
  end
  resources :main, only: :index

  root 'main#index'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
# frozen_string_literal: true

class Car < ApplicationRecord
  NUMBER_REGULAR = /^[а-яё\-\s]{1}[0-9]{3}(?<!0{3})[а-яё\-\s]{2}[0-9]{2}$/.freeze

  belongs_to :user

  validates :number, :manufacturer, :model, presence: true
  validates :number, format: { with: NUMBER_REGULAR, message: 'Number is wrong', multiline: true }

  scope :by_number, ->(number) { where(number: number) }
  scope :by_manufacturer, ->(manufacturer) { where(manufacturer: manufacturer) }
  scope :by_model, ->(model) { where(model: model) }
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  ROLES = %i[admin manager].freeze

  has_many :cars, dependent: :destroy

  devise :database_authenticatable, :registerable, :validatable

  extend Enumerize

  enumerize :role, in: ROLES, predicates: true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include Pundit::Authorization

  rescue_from Pundit::NotAuthorizedError, with: :friendly_redirect

  before_action :authenticate_user!

  private

  def friendly_redirect
    flash[:alert] = 'Access denied'
    redirect_to root_path
  end
end

app/controllers/cars_controller.rb
# frozen_string_literal: true

class CarsController < ApplicationController
  before_action :access_action, only: %i[index new create manager_cars]

  def index
    @cars = Car.page(params[:page] || 1).per(params[:per] || 50)
    @cars = CarsFilter.new(@cars, params).call.order(created_at: :desc)
  end

  def new
    @car = current_user.cars.new
  end

  def create
    @car = current_user.cars.new(car_params)
    exist_car = Car.find_by(car_params)

    if !exist_car && @car.save
      flash[:notice] = "Car added to database"
      redirect_to new_car_path
    elsif exist_car
      flash[:notice] = "Car already exist in database"
      exist_car.update(record_count: exist_car.record_count + 1)
      redirect_to new_car_path
    else
      render :new
    end
  end

  def manager_cars
    @manager = User.find(params[:user_id])
    @cars = @manager.cars
  end

  private

  def access_action
    authorize(nil, policy_class: CarsPolicy)
  end

  def car_params
    params.require(:car).permit(:number, :manufacturer, :model)
  end
end

app/controllers/main_controller.rb
# frozen_string_literal: true

class MainController < ApplicationController
  skip_before_action :authenticate_user!

  def index; end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :access_action

  def index
    @users = User.page(params[:page] || 1).per(params[:per] || 50)
  end

  private

  def access_action
    authorize(nil, policy_class: UsersPolicy)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/cars_helper.rb
# frozen_string_literal: true

module CarsHelper
end

app/helpers/sessions_helper.rb
# frozen_string_literal: true

module SessionsHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/cars/_cars.html.erb
<% cars.each do |car| %>
  <p>
    <%= car.number %>
    &nbsp;
    <%= car.manufacturer %>
    &nbsp;
    <%= car.model %>
    &nbsp;
    Records count: <%= car.record_count %>
  </p>
<% end %>

app/views/cars/index.html.erb
<h1>Auto statistics</h1>

<%= form_tag(cars_path, method: :get) do %>
  <%= label_tag 'Number' %>
  <br>
  <%= text_field_tag(:number, params[:filter]) %>
  <br>
  <%= label_tag 'Manufacturer' %>
  <br>
  <%= text_field_tag(:manufacturer, params[:filter]) %>
  <br>
  <%= label_tag 'Model' %>
  <br>
  <%= text_field_tag(:model, params[:filter]) %>
  <br>
  <%= submit_tag "Search" %>
<% end %>

<%= render partial: 'cars', locals: { cars: @cars } %>

app/views/cars/manager_cars.html.erb
<h4>Added cars by <%= @manager.email %></h4>

<%= render partial: 'cars', locals: { cars: @cars } %>

app/views/cars/new.html.erb
<h2>Add new car</h2>

<%= form_with model: @car, local: true do |f| %>
  <% if @car.errors.any? %>
    <% @car.errors.each do |key, value| %>
      <p><%= value %></p>
    <% end %>
  <% end %>

  <%= f.label 'Number' %>
  <br>
  <%= f.text_field :number %>
  <br>
  <%= f.label 'Manufacturer' %>
  <br>
  <%= f.text_field :manufacturer %>
  <br>
  <%= f.label 'Model' %>
  <br>
  <%= f.text_field :model %>
  <br>
  <%= f.submit 'Add' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CarAccounting</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if signed_in? %>
      <%= link_to 'Search cars', cars_path %>
      &nbsp;
      <%= link_to 'Managers', users_path %>
      &nbsp;
      <%= link_to 'Add car to DB', new_car_path %>
      &nbsp;
      <%= current_user.role %>
      &nbsp;
      <%= link_to 'Sign out', destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to 'Sign in', new_user_session_path %>
      <%= link_to 'Sign up', new_user_registration_path %>
    <% end %>
    
    <% if flash %>
      <br><br>
      <% flash.each do |key, value| %>
        <%= "#{key}: #{value}" %>
      <% end %>
      <br>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/main/index.html.erb
<h1>Main</h1>

app/views/users/index.html.erb
<h1>Managers</h1>

<% @users.each do |user| %>
  <p>
    <%= user.email %>
    &nbsp;
    <%= link_to 'Added cars', "/cars/manager_cars/#{user.id}" %>
  </p>
<% end %>